sites:
  - name: Main Server
    description: This is a server.
    status: 2
    children:
      - name: Service 1
        description: This is a demo for p.mume.
        status: 1
      - name: Service 2
        description: This is a demo for p.mume.
        status: 2
      - name: Service 3
        description: This is a demo for p.mume.
        status: 3
  - name: Second Server
    description: This is a server, too.
    status: 2
    children:
      - name: Service
        description: This is a demo for p.mume.
        status: 0
